package io.testproject.generated.tests.myfirstproject;

import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import java.lang.Exception;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;

/**
 * This class was automatically generated by TestProject
 * Project: My first Project
 * Test: CP006
 * Generated by: Channyke Rodriguez (csrodriguez21@ucatolica.edu.co)
 * Generated on Wed Oct 13 00:59:36 GMT 2021.
 */
@DisplayName("CP006")
public class Cp006 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("Dl_CRrVGkr6XQ2tp-Eg4dJ3yWlOTRQ7XPZwrxjLFM_0", new ChromeOptions(), "Channyke Rodriguez");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("CP006")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String Idtarea, String usuario) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;

    // 1. Navigate to '{{ApplicationURL}}'
    //    Navigates the specified URL (Auto-generated)
    GeneratedUtils.sleep(500);
    driver.navigate().to(ApplicationURL);

    // 2. Click 'user'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#user");
    driver.findElement(by).click();

    // 3. Type 'jdme1' in 'user'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#user");
    driver.findElement(by).sendKeys("jdme1");

    // 4. Click 'password'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#password");
    driver.findElement(by).click();

    // 5. Type 'lindo123!' in 'password'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#password");
    driver.findElement(by).sendKeys("lindo123!");

    // 6. Click 'Log in'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#ingresar");
    driver.findElement(by).click();

    // 7. Scroll window by ('0','500')
    GeneratedUtils.sleep(500);
    ((JavascriptExecutor)driver).executeScript("window.scrollBy(0,500)","");

    // 8. Click 'Share Task'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#shareTask");
    driver.findElement(by).click();

    // 9. Click 'IDtask'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#IDtask");
    driver.findElement(by).click();

    // 10. Type '{{Idtarea}}' in 'IDtask'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#IDtask");
    driver.findElement(by).sendKeys(Idtarea);

    // 11. Scroll window by ('0','56')
    GeneratedUtils.sleep(500);
    ((JavascriptExecutor)driver).executeScript("window.scrollBy(0,56)","");

    // 12. Click 'user'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#user");
    driver.findElement(by).click();

    // 13. Type '{{usuario}}' in 'user'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#user");
    driver.findElement(by).sendKeys(usuario);

    // 14. Click 'Compartir'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#share");
    driver.findElement(by).click();

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("http://localhost/ActiveTime/","25","Deiv8"));
  }
}
