from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP006
    Generated by: Channyke Rodriguez (csrodriguez21@ucatolica.edu.co)
    Generated on 10/13/2021, 01:01:49
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Dl_CRrVGkr6XQ2tp-Eg4dJ3yWlOTRQ7XPZwrxjLFM_0",
                              project_name="My first Project",
                              job_name="CP006")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """El sistema mostrará la interfaz en la que el usuario podrá interactuar con algunos de los datos de sus tareas para compartirlas a otros usuarios."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/ActiveTime/"
    Idtarea = "25"
    usuario = "Deiv8"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.click()

    # 3. Type 'jdme1' in 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.send_keys("jdme1")

    # 4. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 5. Type 'lindo123!' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys("lindo123!")

    # 6. Click 'Log in'
    log_in = driver.find_element(By.CSS_SELECTOR,
                                 "#ingresar")
    log_in.click()

    # 7. Scroll window by ('0','500')
    driver.execute_script("window.scrollBy(0,500)")

    # 8. Click 'Share Task'
    share_task = driver.find_element(By.CSS_SELECTOR,
                                     "#shareTask")
    share_task.click()

    # 9. Click 'IDtask'
    idtask = driver.find_element(By.CSS_SELECTOR,
                                 "#IDtask")
    idtask.click()

    # 10. Type '{Idtarea}' in 'IDtask'
    idtask = driver.find_element(By.CSS_SELECTOR,
                                 "#IDtask")
    idtask.send_keys(f'{Idtarea}')

    # 11. Scroll window by ('0','56')
    driver.execute_script("window.scrollBy(0,56)")

    # 12. Click 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.click()

    # 13. Type '{usuario}' in 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.send_keys(f'{usuario}')

    # 14. Click 'Compartir'
    compartir = driver.find_element(By.CSS_SELECTOR,
                                    "#share")
    compartir.click()
